name: hackernews-daily

on:
  schedule:
    - cron: "1 0 * * *"
  workflow_dispatch:
jobs:
  fetch-top-posts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 19.x
      - name: npm install
        run: npm install --only=prod
        working-directory: .
      - name: fetch
        run: node index.js
        working-directory: .
        # for github token
        env:
          TOKEN: ${{ secrets.ISSUES_TOKEN }}
